### ISSUE TITLE
Proposal for Adding CITATION File to the Project

### ISSUE THREAD

**Issue by AndreAugusto11** [CrosschainRiskFramework/CrosschainRiskFramework.github.io#106]
I suggest implementing a CITATION file (refer to [GitHub Docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files)).

Having a CITATION file would benefit both the creators and researchers who wish to cite the work conducted in this project accurately. It would serve as a standardized reference for citing this project in academic publications, research papers, or any other work where proper citation is crucial.

**Comment by ermyas** [comment]
Hi @AndreAugusto11 - Thanks for the great suggestion. I'll add a citation file shortly.
