### ISSUE TITLE
Update protocol implementation risk

### ISSUE THREAD

**Issue by ermyas** [CrosschainRiskFramework/CrosschainRiskFramework.github.io#12]
Cross-chain protocols are complex systems with various components spanning multiple ecosystems. The implementation of such software and the low-level design decisions towards this end can be a source of risk. This often manifests in the form of software bugs (logic bugs, dependency vulnerabilities, etc.). This has been a predominant cause of the bridge failures experienced over the last couple of years. 

This section lays out this type of risk in more detail and discusses various considerations and mitigation strategies associated with this type of risk.

**Comment by drinkcoffee** [comment]
Issue: https://github.com/CrosschainRiskFramework/CrosschainRiskFramework.github.io/issues/15  addresses a subset of this issue.

**Comment by drinkcoffee** [comment]
I suggest we close this broad issue, and open smaller issues to revise individual sections, re-order the sections, or add new sections, or remove sections that no longer make sense.

Thoughts @ermyas @ArjunChand13 @vaibhavchellani

**Comment by ermyas** [comment]
Ideally, this would have served as an epic or a parent issue under which we would have more granular issues. Given the limitations of creating issue hierarchies in Github (without relying on add-ons), I agree this would be a bit confusing.
