### ISSUE TITLE
Update protocol operational risk

### ISSUE THREAD

**Issue by ermyas** [CrosschainRiskFramework/CrosschainRiskFramework.github.io#13]
The operation of a cross-chain bridge involves the management of various components, potentially operated by distinct actors. Such activities could include the upgrade and management of bridge smart contracts and the operation of various off-chain systems (e.g. external validator nodes). Having robust, secure, decentralized, and transparent mechanisms, processes, and policies for managing such systems is crucial to ensuring the security of cross-chain bridges. 

This section lays out this type of risk in more detail and discusses various considerations and mitigation strategies associated with this type of risk.

**Comment by drinkcoffee** [comment]
Parts of this section have been enhanced. I am closing this issue. Other more focused issues can be opened in its place.
