### ISSUE TITLE
Protocol Implementation Risk: Code Auditing section

### ISSUE THREAD

**Issue by drinkcoffee** [CrosschainRiskFramework/CrosschainRiskFramework.github.io#51]
The Protocol Implementation Risk: Code Auditing section needs to be reworked.

**Comment by ArjunChand13** [comment]
@drinkcoffee I've created a PR of this section for review here - https://github.com/CrosschainRiskFramework/CrosschainRiskFramework.github.io/pull/64#issue-1494211766

**Comment by drinkcoffee** [comment]
A PR for this issue has been merged.
