### ISSUE TITLE
Review document prior to release of v0.1.0

### ISSUE THREAD

**Issue by ermyas** [CrosschainRiskFramework/CrosschainRiskFramework.github.io#85]
This task involves reviewing the framework end-to-end prior to the public release of v0.1.0 mid-next week (8th February). 
Please reference this issue as you submit PRs or create issues as part of your review. 
Once you are comfortable with the document, please add a comment to that effect below.

**Comment by drinkcoffee** [comment]
LGTM

I think the content is ready enough for publication and collaboration. There is definitely more work to be done: sections to be reworked and sections to be completed. Most notably, the section on assessment of risk. These sections can be improved over time.

**Comment by vaibhavchellani** [comment]
LGTM!

**Comment by ArjunChand13** [comment]
LGTM! :) Still more work to do here, but it's ready to be published.

**Comment by ermyas** [comment]
LGTM as an initial release. 
There is still a fair bit of work to do. The section around risk scoring in particular needs to be carefully thought through. However, we are probably at a stage where feedback from the broader community can better shape how this evolves.
